name: Docker Build Hubitat Device Events (AMD64)

on:
  push:

  workflow_dispatch:
    inputs:
        tag:
          description: 'Define the tag to use for the build'
          required: true
          default: 'welasco/hubitat-device-events:latest, welasco/hubitat-device-events:v1.0.0'
          type: string

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push linux/amd64
        id: docker_build_amd64
        uses: docker/build-push-action@v5
        with:
          #context: ./Alarm/
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: "${{ github.event.inputs.tag }}"